/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IngestionRouteImport } from './routes/ingestion'
import { Route as MigrationsRouteImport } from './routes/migrations'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as PProcessKeyIndexRouteImport } from './routes/p.$processKey.index'
import { Route as PProcessKeyBottlenecksRouteImport } from './routes/p.$processKey.bottlenecks'
import { Route as PProcessKeyExplorerRouteImport } from './routes/p.$processKey.explorer'
import { Route as PProcessKeyOverviewRouteImport } from './routes/p.$processKey.overview'
import { Route as PProcessKeyReworkRouteImport } from './routes/p.$processKey.rework'
import { Route as PProcessKeySlaRouteImport } from './routes/p.$processKey.sla'
import { Route as PProcessKeyVariantsRouteImport } from './routes/p.$processKey.variants'
import { Route as PProcessKeyCasesIndexRouteImport } from './routes/p.$processKey.cases.index'
import { Route as PProcessKeyCasesCaseIdRouteImport } from './routes/p.$processKey.cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestionRoute = IngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationsRoute = MigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProcessKeyIndexRoute = PProcessKeyIndexRouteImport.update({
  id: '/p/$processKey/',
  path: '/p/$processKey/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProcessKeyBottlenecksRoute = PProcessKeyBottlenecksRouteImport.update({
  id: '/p/$processKey/bottlenecks',
  path: '/p/$processKey/bottlenecks',
  getParentRoute: () => rootRouteImport,
} as any)
const PProcessKeyExplorerRoute = PProcessKeyExplorerRouteImport.update({
  id: '/p/$processKey/explorer',
  path: '/p/$processKey/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const PProcessKeyOverviewRoute = PProcessKeyOverviewRouteImport.update({
  id: '/p/$processKey/overview',
  path: '/p/$processKey/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PProcessKeyReworkRoute = PProcessKeyReworkRouteImport.update({
  id: '/p/$processKey/rework',
  path: '/p/$processKey/rework',
  getParentRoute: () => rootRouteImport,
} as any)
const PProcessKeySlaRoute = PProcessKeySlaRouteImport.update({
  id: '/p/$processKey/sla',
  path: '/p/$processKey/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const PProcessKeyVariantsRoute = PProcessKeyVariantsRouteImport.update({
  id: '/p/$processKey/variants',
  path: '/p/$processKey/variants',
  getParentRoute: () => rootRouteImport,
} as any)
const PProcessKeyCasesIndexRoute = PProcessKeyCasesIndexRouteImport.update({
  id: '/p/$processKey/cases/',
  path: '/p/$processKey/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProcessKeyCasesCaseIdRoute = PProcessKeyCasesCaseIdRouteImport.update({
  id: '/p/$processKey/cases/$caseId',
  path: '/p/$processKey/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datasets': typeof DatasetsRoute
  '/health': typeof HealthRoute
  '/ingestion': typeof IngestionRoute
  '/migrations': typeof MigrationsRoute
  '/processes': typeof ProcessesRoute
  '/settings': typeof SettingsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/p/$processKey/bottlenecks': typeof PProcessKeyBottlenecksRoute
  '/p/$processKey/explorer': typeof PProcessKeyExplorerRoute
  '/p/$processKey/overview': typeof PProcessKeyOverviewRoute
  '/p/$processKey/rework': typeof PProcessKeyReworkRoute
  '/p/$processKey/sla': typeof PProcessKeySlaRoute
  '/p/$processKey/variants': typeof PProcessKeyVariantsRoute
  '/p/$processKey/': typeof PProcessKeyIndexRoute
  '/p/$processKey/cases/$caseId': typeof PProcessKeyCasesCaseIdRoute
  '/p/$processKey/cases/': typeof PProcessKeyCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datasets': typeof DatasetsRoute
  '/health': typeof HealthRoute
  '/ingestion': typeof IngestionRoute
  '/migrations': typeof MigrationsRoute
  '/processes': typeof ProcessesRoute
  '/settings': typeof SettingsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/p/$processKey/bottlenecks': typeof PProcessKeyBottlenecksRoute
  '/p/$processKey/explorer': typeof PProcessKeyExplorerRoute
  '/p/$processKey/overview': typeof PProcessKeyOverviewRoute
  '/p/$processKey/rework': typeof PProcessKeyReworkRoute
  '/p/$processKey/sla': typeof PProcessKeySlaRoute
  '/p/$processKey/variants': typeof PProcessKeyVariantsRoute
  '/p/$processKey': typeof PProcessKeyIndexRoute
  '/p/$processKey/cases/$caseId': typeof PProcessKeyCasesCaseIdRoute
  '/p/$processKey/cases': typeof PProcessKeyCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datasets': typeof DatasetsRoute
  '/health': typeof HealthRoute
  '/ingestion': typeof IngestionRoute
  '/migrations': typeof MigrationsRoute
  '/processes': typeof ProcessesRoute
  '/settings': typeof SettingsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/p/$processKey/bottlenecks': typeof PProcessKeyBottlenecksRoute
  '/p/$processKey/explorer': typeof PProcessKeyExplorerRoute
  '/p/$processKey/overview': typeof PProcessKeyOverviewRoute
  '/p/$processKey/rework': typeof PProcessKeyReworkRoute
  '/p/$processKey/sla': typeof PProcessKeySlaRoute
  '/p/$processKey/variants': typeof PProcessKeyVariantsRoute
  '/p/$processKey/': typeof PProcessKeyIndexRoute
  '/p/$processKey/cases/$caseId': typeof PProcessKeyCasesCaseIdRoute
  '/p/$processKey/cases/': typeof PProcessKeyCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datasets'
    | '/health'
    | '/ingestion'
    | '/migrations'
    | '/processes'
    | '/settings'
    | '/events/$eventId'
    | '/p/$processKey/bottlenecks'
    | '/p/$processKey/explorer'
    | '/p/$processKey/overview'
    | '/p/$processKey/rework'
    | '/p/$processKey/sla'
    | '/p/$processKey/variants'
    | '/p/$processKey/'
    | '/p/$processKey/cases/$caseId'
    | '/p/$processKey/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datasets'
    | '/health'
    | '/ingestion'
    | '/migrations'
    | '/processes'
    | '/settings'
    | '/events/$eventId'
    | '/p/$processKey/bottlenecks'
    | '/p/$processKey/explorer'
    | '/p/$processKey/overview'
    | '/p/$processKey/rework'
    | '/p/$processKey/sla'
    | '/p/$processKey/variants'
    | '/p/$processKey'
    | '/p/$processKey/cases/$caseId'
    | '/p/$processKey/cases'
  id:
    | '__root__'
    | '/'
    | '/datasets'
    | '/health'
    | '/ingestion'
    | '/migrations'
    | '/processes'
    | '/settings'
    | '/events/$eventId'
    | '/p/$processKey/bottlenecks'
    | '/p/$processKey/explorer'
    | '/p/$processKey/overview'
    | '/p/$processKey/rework'
    | '/p/$processKey/sla'
    | '/p/$processKey/variants'
    | '/p/$processKey/'
    | '/p/$processKey/cases/$caseId'
    | '/p/$processKey/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasetsRoute: typeof DatasetsRoute
  HealthRoute: typeof HealthRoute
  IngestionRoute: typeof IngestionRoute
  MigrationsRoute: typeof MigrationsRoute
  ProcessesRoute: typeof ProcessesRoute
  SettingsRoute: typeof SettingsRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  PProcessKeyBottlenecksRoute: typeof PProcessKeyBottlenecksRoute
  PProcessKeyExplorerRoute: typeof PProcessKeyExplorerRoute
  PProcessKeyOverviewRoute: typeof PProcessKeyOverviewRoute
  PProcessKeyReworkRoute: typeof PProcessKeyReworkRoute
  PProcessKeySlaRoute: typeof PProcessKeySlaRoute
  PProcessKeyVariantsRoute: typeof PProcessKeyVariantsRoute
  PProcessKeyIndexRoute: typeof PProcessKeyIndexRoute
  PProcessKeyCasesCaseIdRoute: typeof PProcessKeyCasesCaseIdRoute
  PProcessKeyCasesIndexRoute: typeof PProcessKeyCasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingestion': {
      id: '/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof IngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrations': {
      id: '/migrations'
      path: '/migrations'
      fullPath: '/migrations'
      preLoaderRoute: typeof MigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$processKey/': {
      id: '/p/$processKey/'
      path: '/p/$processKey'
      fullPath: '/p/$processKey/'
      preLoaderRoute: typeof PProcessKeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$processKey/bottlenecks': {
      id: '/p/$processKey/bottlenecks'
      path: '/p/$processKey/bottlenecks'
      fullPath: '/p/$processKey/bottlenecks'
      preLoaderRoute: typeof PProcessKeyBottlenecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$processKey/explorer': {
      id: '/p/$processKey/explorer'
      path: '/p/$processKey/explorer'
      fullPath: '/p/$processKey/explorer'
      preLoaderRoute: typeof PProcessKeyExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$processKey/overview': {
      id: '/p/$processKey/overview'
      path: '/p/$processKey/overview'
      fullPath: '/p/$processKey/overview'
      preLoaderRoute: typeof PProcessKeyOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$processKey/rework': {
      id: '/p/$processKey/rework'
      path: '/p/$processKey/rework'
      fullPath: '/p/$processKey/rework'
      preLoaderRoute: typeof PProcessKeyReworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$processKey/sla': {
      id: '/p/$processKey/sla'
      path: '/p/$processKey/sla'
      fullPath: '/p/$processKey/sla'
      preLoaderRoute: typeof PProcessKeySlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$processKey/variants': {
      id: '/p/$processKey/variants'
      path: '/p/$processKey/variants'
      fullPath: '/p/$processKey/variants'
      preLoaderRoute: typeof PProcessKeyVariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$processKey/cases/': {
      id: '/p/$processKey/cases/'
      path: '/p/$processKey/cases'
      fullPath: '/p/$processKey/cases/'
      preLoaderRoute: typeof PProcessKeyCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$processKey/cases/$caseId': {
      id: '/p/$processKey/cases/$caseId'
      path: '/p/$processKey/cases/$caseId'
      fullPath: '/p/$processKey/cases/$caseId'
      preLoaderRoute: typeof PProcessKeyCasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetsRoute: DatasetsRoute,
  HealthRoute: HealthRoute,
  IngestionRoute: IngestionRoute,
  MigrationsRoute: MigrationsRoute,
  ProcessesRoute: ProcessesRoute,
  SettingsRoute: SettingsRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  PProcessKeyBottlenecksRoute: PProcessKeyBottlenecksRoute,
  PProcessKeyExplorerRoute: PProcessKeyExplorerRoute,
  PProcessKeyOverviewRoute: PProcessKeyOverviewRoute,
  PProcessKeyReworkRoute: PProcessKeyReworkRoute,
  PProcessKeySlaRoute: PProcessKeySlaRoute,
  PProcessKeyVariantsRoute: PProcessKeyVariantsRoute,
  PProcessKeyIndexRoute: PProcessKeyIndexRoute,
  PProcessKeyCasesCaseIdRoute: PProcessKeyCasesCaseIdRoute,
  PProcessKeyCasesIndexRoute: PProcessKeyCasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
